name: wheretf
description: WhereToFind private location sharing app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.4
  google_fonts: ^6.2.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  http_parser: ^4.1.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon_square.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/app_icon_square.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/app_icon_square.png"
    background_color: "#000000"
    theme_color: "#000000"
